version: "3.5"

services:
  chat-dtb:
    container_name: "chatdtb"
    image: mongo
    restart: always
    ports:
      - "8283:27017"
      - "8284:28017"
    volumes:
      - ./Database/data:/data/db
    networks:
      chat_net:
        ipv4_address: 10.1.2.2
  chat-service:
    container_name: "chatservice"
    depends_on:
      - chat-dtb
      - chat-cdn
    build:
      context: ./JavaBackend
      dockerfile: dockerfile.javadev
    restart: always
    ports:
      - "8081:8002"
    volumes:
      - ./JavaBackend:/app
    networks:
      chat_net:
        ipv4_address: 10.1.2.3
  chat-cdn:
    container_name: "chatcdn"
    build:
      context: ./CDNServer
      dockerfile: dockerfile.cdn
    ports:
      - "8082:8888"
    volumes:
      - ./CDNServer:/app/Backend/CDNServer
      - ./CDNServer/go.mod:/app/Backend/CDNServer/go.mod
    networks:
      chat_net:
        ipv4_address: 10.1.2.4

networks:
  chat_net:
    ipam:
      driver: default
      config:
        - subnet: "10.1.2.0/27"
