version: "3.5"

services:
  chat-dtb:
    container_name: "chatdtb"
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    networks:
      chat_net:
        ipv4_address: 10.1.2.2
  chat-service:
    container_name: "chatservice"
    depends_on:
      - chat-dtb
    build:
      context: ./
      dockerfile: dockerfile
    entrypoint: ["./mvnw.sh", "spring-boot:run"]
    restart: always
    ports:
      - "8081:8002"
    volumes:
      - ./:/app
    networks:
      chat_net:
        ipv4_address: 10.1.2.3

networks:
  chat_net:
    ipam:
      driver: default
      config:
        - subnet: "10.1.2.0/27"
